version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # app source code for easier development. Remove for production (?).
      - .:/app
    environment:
      - PORT=3000
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/sql:/data/sql
    restart: always