# Generated by Django 5.1.6 on 2025-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infantum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_id', models.CharField(blank=True, db_column='Gene_ID', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('other_names', models.CharField(blank=True, db_column='Other_names', max_length=255, null=True)),
                ('wikidata', models.CharField(blank=True, db_column='Wikidata', max_length=200, null=True)),
                ('mendeley', models.CharField(blank=True, db_column='Mendeley', max_length=200, null=True)),
                ('uniprot', models.CharField(blank=True, db_column='UniProt', max_length=200, null=True)),
                ('lmjf_ortholog', models.CharField(blank=True, db_column='LmjF_ortholog', max_length=255, null=True)),
                ('lmjfc_ortholog', models.CharField(blank=True, db_column='LmjFC_ortholog', max_length=255, null=True)),
                ('ldhu3_ortholog', models.CharField(blank=True, db_column='LdHU3_ortholog', max_length=255, null=True)),
                ('lbrm2904_ortholog', models.CharField(blank=True, db_column='LBRM2904_ortholog', max_length=255, null=True)),
            ],
            options={
                'db_table': 'infantum',
                'managed': False,
            },
        ),
    ]
